### ISSUE TITLE
data_visualizer run.py error

### ISSUE THREAD

**Issue by edisonchan** [oblalex/nvidia-gpu-monitoring#2]
```
D:\backup\benchmark\GPUPerfTest_v0.9.0>.\data_visualizer\run.py .\output\output.0.png extracted.csv
Drawing full window to '.\output\output.0.png'
Traceback (most recent call last):
  File "D:\backup\benchmark\GPUPerfTest_v0.9.0\data_visualizer\run.py", line 252, in <module>
    main()
  File "D:\backup\benchmark\GPUPerfTest_v0.9.0\data_visualizer\run.py", line 234, in main
    draw_full_window(
  File "D:\backup\benchmark\GPUPerfTest_v0.9.0\data_visualizer\run.py", line 180, in draw_full_window
    draw_figure(
  File "D:\backup\benchmark\GPUPerfTest_v0.9.0\data_visualizer\run.py", line 162, in draw_figure
    plt.savefig(
  File "C:\Users\edison\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\pyplot.py", line 942, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\Users\edison\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\figure.py", line 3272, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\edison\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "C:\Users\edison\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "C:\Users\edison\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\_api\deprecation.py", line 385, in wrapper
    arguments = signature.bind(*inner_args, **inner_kwargs).arguments
  File "C:\Users\edison\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 3179, in bind
    return self._bind(args, kwargs)
  File "C:\Users\edison\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 3168, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'legend'
```

The list for installed Python modules in my Windows"
```
Package              Version
-------------------- -----------
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.8
attrs                22.1.0
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.1
cffi                 1.15.1
colorama             0.4.5
contourpy            1.0.5
cycler               0.11.0
debugpy              1.6.3
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
executing            1.1.0
fastjsonschema       2.16.2
fonttools            4.37.3
ipykernel            6.15.3
ipython              8.5.0
ipython-genutils     0.2.0
ipywidgets           8.0.2
jedi                 0.18.1
Jinja2               3.1.2
jsonschema           4.16.0
jupyter              1.0.0
jupyter_client       7.3.5
jupyter-console      6.4.4
jupyter-core         4.11.1
jupyterlab-pygments  0.2.2
jupyterlab-widgets   3.0.3
kiwisolver           1.4.4
lxml                 4.9.1
MarkupSafe           2.1.1
matplotlib           3.6.0
matplotlib-inline    0.1.6
mistune              2.0.4
nbclient             0.6.8
nbconvert            7.0.0
nbformat             5.6.0
nest-asyncio         1.5.5
notebook             6.4.12
numpy                1.23.3
packaging            21.3
pandas               1.5.0
pandocfilters        1.5.0
parso                0.8.3
pickleshare          0.7.5
Pillow               9.2.0
pip                  22.2.2
prometheus-client    0.14.1
prompt-toolkit       3.0.31
psutil               5.9.2
pure-eval            0.2.2
pycparser            2.21
Pygments             2.13.0
pyparsing            3.0.9
pyrsistent           0.18.1
python-dateutil      2.8.2
pytz                 2022.2.1
pywin32              304
pywinpty             2.0.8
pyzmq                24.0.1
qtconsole            5.3.2
QtPy                 2.2.0
Send2Trash           1.8.0
setuptools           63.2.0
six                  1.16.0
soupsieve            2.3.2.post1
stack-data           0.5.1
terminado            0.15.0
tinycss2             1.1.1
tornado              6.2
traitlets            5.4.0
wcwidth              0.2.5
webencodings         0.5.1
widgetsnbextension   4.0.3
```

**Comment by oblalex** [comment]
Hello! Thank you for your interest in this project and for pointing out this issue.

I assume that some internal API of the `matplotlib` has changed. Could you please check if removing the [`legend=False`](https://github.com/oblalex/nvidia-gpu-monitoring/blob/bde14626cd61b2e747ca5d6d0f43afeed076edba/data_visualizer/run.py#L165) param for `plt.savefig()` fixes the issue?

Regards

**Comment by edisonchan** [comment]
> Hello! Thank you for your interest in this project and for pointing out this issue.
> 
> I assume that some internal API of the `matplotlib` has changed. Could you please check if removing the [`legend=False`](https://github.com/oblalex/nvidia-gpu-monitoring/blob/bde14626cd61b2e747ca5d6d0f43afeed076edba/data_visualizer/run.py#L165) param for `plt.savefig()` fixes the issue?
> 
> Regards

It works, Thank you very much.
